- name: Terraform and Ansible Integration
  hosts: all

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: suse.yml
  when: ansible_os_family == 'Suse'
    