- name: Add epel-release repo
  yum:
    name: epel-release
    state: latest
  become: True

- name: Install nginx
  yum:
    name: nginx
    state: present
  become: True

- name: Start NGiNX
  service:
    name: nginx
    state: started
  become: True