- name: Install EPEL release (REDHAT)
  yum: 
    name: epel-release 
    state: present
    
- name: Install nginx web server(REDHAT)
  yum: 
    name: nginx 
    state: present
    update_cache: true
  notify:
    - start nginx
    
- name: start nginx 
  service:
    name: nginx
    enabled: yes
    state: started